services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER: ${USER} # same as your host user
        USER_UID: ${UID:-1000}
    volumes:
      - .:/home/${USER}/heapdog:cached
      - jetbrains_cache:/home/${USER}/.cache/JetBrains
      - vscode_server:/home/${USER}/.vscode-server
    ports:
      - 8080:8080
    env_file:
      - .env
    working_dir: /home/${USER}/heapdog
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER:-postgres}", "-d", "${DB_NAME:-heapdog}" ]
      interval: 5s
      retries: 3

  backend:
    container_name: backend-prod
    image: ${BACKEND_IMAGE:-backend-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      JAVA_OPTS: ${JAVA_OPTS:-}
      SERVER_PORT: ${SERVER_PORT:-8080}

    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:${SERVER_PORT:-8080}/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      - heapdog-network


  db:
    container_name: db-prod
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-}
      POSTGRES_DB: ${DB_NAME:-heapdog}
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - heapdog-network


  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    working_dir: /home/gradle/app
    environment:
      SPRING_PROFILES_ACTIVE: test
    volumes:
      - .:/home/gradle/app
      - ./build/reports:/home/gradle/app/build/reports
    command: [ "./gradlew", "test", "jacocoTestReport", "--info" ]

volumes:
  db_data_prod:
  jetbrains_cache:
  vscode_server:

networks:
  heapdog-network:
    external: true