CREATE TABLE heapdog_service_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_by_id BIGINT,
    is_deleted    BOOLEAN                                 NOT NULL,
    name          VARCHAR(255),
    api_key       VARCHAR(255),
    enabled       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_heapdog_service_user PRIMARY KEY (id)
);

CREATE TABLE heapdog_service_user_permission
(
    service_user_id BIGINT NOT NULL,
    permission      VARCHAR(255)
);

ALTER TABLE heapdog_service_user
    ADD CONSTRAINT FK_HEAPDOG_SERVICE_USER_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES heapdog_user (id);

ALTER TABLE heapdog_service_user
    ADD CONSTRAINT FK_HEAPDOG_SERVICE_USER_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES heapdog_user (id);

ALTER TABLE heapdog_service_user_permission
    ADD CONSTRAINT fk_heapdog_service_user_permission_on_service_user FOREIGN KEY (service_user_id) REFERENCES heapdog_service_user (id);