CREATE TABLE notification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_by_id BIGINT,
    is_deleted    BOOLEAN                                 NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    message       VARCHAR(200)                            NOT NULL,
    link          VARCHAR(255),
    is_read       BOOLEAN                                 NOT NULL,
    is_clicked    BOOLEAN                                 NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES heapdog_user (id);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES heapdog_user (id);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_USER FOREIGN KEY (user_id) REFERENCES heapdog_user (id);