CREATE TABLE organization
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_by_id BIGINT,
    is_deleted    BOOLEAN                                 NOT NULL,
    org_name      VARCHAR(255)                            NOT NULL,
    slug          VARCHAR(255)                            NOT NULL,
    description   VARCHAR(1000),
    email         VARCHAR(500),
    website       VARCHAR(500),
    address       VARCHAR(1000),
    phone         VARCHAR(20),
    CONSTRAINT pk_organization PRIMARY KEY (id)
);

ALTER TABLE organization
    ADD CONSTRAINT uc_organization_slug UNIQUE (slug);

ALTER TABLE organization
    ADD CONSTRAINT FK_ORGANIZATION_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES heapdog_user (id);

ALTER TABLE organization
    ADD CONSTRAINT FK_ORGANIZATION_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES heapdog_user (id);