CREATE TABLE membership
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    is_deleted      BOOLEAN                                 NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    role            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_membership PRIMARY KEY (id)
);

ALTER TABLE membership
    ADD CONSTRAINT FK_MEMBERSHIP_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES heapdog_user (id);

ALTER TABLE membership
    ADD CONSTRAINT FK_MEMBERSHIP_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id);

ALTER TABLE membership
    ADD CONSTRAINT FK_MEMBERSHIP_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES heapdog_user (id);

ALTER TABLE membership
    ADD CONSTRAINT FK_MEMBERSHIP_ON_USER FOREIGN KEY (user_id) REFERENCES heapdog_user (id);