CREATE TABLE organization_invitation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    is_deleted      BOOLEAN                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    code            VARCHAR(255),
    is_accepted     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_organization_invitation PRIMARY KEY (id)
);

ALTER TABLE organization_invitation
    ADD CONSTRAINT FK_ORGANIZATION_INVITATION_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES heapdog_user (id);

ALTER TABLE organization_invitation
    ADD CONSTRAINT FK_ORGANIZATION_INVITATION_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id);

ALTER TABLE organization_invitation
    ADD CONSTRAINT FK_ORGANIZATION_INVITATION_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES heapdog_user (id);

ALTER TABLE organization_invitation
    ADD CONSTRAINT FK_ORGANIZATION_INVITATION_ON_USER FOREIGN KEY (user_id) REFERENCES heapdog_user (id);